USE [master]
GO

/****** Object:  Database [UPIAV_ELECCIONES]    Script Date: 18/9/2022 12:09:37:PM ******/
CREATE DATABASE [UPIAV_ELECCIONES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UPIAV_ELECCIONES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\UPIAV_ELECCIONES.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UPIAV_ELECCIONES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\UPIAV_ELECCIONES_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UPIAV_ELECCIONES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ARITHABORT OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET  MULTI_USER 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UPIAV_ELECCIONES] SET  READ_WRITE 
GO

